FROM python:latest

ENV INSTALL_DIR=/opt/conjur-openapi-spec

RUN apt-get update && \
    apt-get install -y bash \
                       binutils \
                       build-essential \
                       git \
                       jq

RUN mkdir -p $INSTALL_DIR
WORKDIR $INSTALL_DIR

COPY requirements.txt $INSTALL_DIR/
RUN pip3 install -r requirements.txt

COPY . $INSTALL_DIR

ARG APPLIANCE
RUN pip3 install -e out/${APPLIANCE:-oss}/python/
