FROM ubuntu:20.04

WORKDIR /cyberark

RUN apt-get update && \
    apt-get install -y build-essential \
                       python3 \
                       python3-dev \
                       python3-pip

COPY spec.yml .

RUN pip3 install schemathesis
