FROM ubuntu:latest

WORKDIR /cyberark

RUN apt-get update && \
    apt-get install -y build-essential \
                       python3 \
                       python3-dev \
                       python3-pip

COPY ./conjur-openapi.yml .

RUN pip3 install schemathesis
