/*
 * Conjur
 * This is an API definition for CyberArk Conjur OSS. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.api;

import org.conjur.sdk.*;
import org.conjur.sdk.api.*;
import org.conjur.sdk.model.*;

import org.junit.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResourcesApi
 */
public class ResourcesApiTest extends ConfiguredTest {

    private final ResourcesApi api = new ResourcesApi();

    
    /**
     * Shows a description of a single resource.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showResourceTest() throws ApiException {
        String kind = "variable";
        String identifier = "testSecret";
        Boolean permittedRoles = null;
        String privilege = null;
        Boolean check = null;
        String role = null;
        String xRequestId = null;
        ApiResponse<Resource> response = api.showResourceWithHttpInfo(account, kind, identifier, permittedRoles, privilege, check, role, xRequestId);

        Assert.assertEquals(200, response.getStatusCode());
        Resource result = response.getData();
        Assert.assertEquals(String.format("%s:variable:testSecret", account), result.getId());
    }
    
    /**
     * Lists resources within an organization account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showResourcesForAccountTest() throws ApiException {
        String kind = "variable";
        String search = null;
        Integer offset = null;
        Integer limit = null;
        Boolean count = null;
        String role = null;
        String actingAs = null;
        String xRequestId = null;

        ApiResponse<List<Resource>> response = api.showResourcesForAccountWithHttpInfo(account, kind, search, offset, limit, count, role, actingAs, xRequestId);
        Assert.assertEquals(200, response.getStatusCode());
    }
    
    /**
     * Lists resources within an organization account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showResourcesForAllAccountsTest() throws ApiException {
        String kind = null;
        String search = null;
        Integer offset = null;
        Integer limit = null;
        Boolean count = null;
        String role = null;
        String actingAs = null;
        String xRequestId = null;
        ApiResponse<List<Resource>> response = api.showResourcesForAllAccountsWithHttpInfo(account, kind, search, offset, limit, count, role, actingAs, xRequestId);

        Assert.assertEquals(200, response.getStatusCode());
    }
    
    /**
     * Lists resources of the same kind within an organization account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showResourcesForKindTest() throws ApiException {
        String kind = "variable";
        String search = null;
        Integer offset = null;
        Integer limit = null;
        Boolean count = null;
        String role = null;
        String actingAs = null;
        String xRequestId = null;

        ApiResponse<List<Resource>> response = api.showResourcesForKindWithHttpInfo(account, kind, search, offset, limit, count, role, actingAs, xRequestId);
        Assert.assertEquals(200, response.getStatusCode());
    }
    
}
