#!/usr/bin/env bash
set -e
. bin/util

bin/generate_kong_config

host_option=""
# configure `docker run` --add-host to allow Kong to target other
# containers on the host network. Docker for Mac/Windows pre-configures
# host.docker.interal to point to the container host network
if [ "$(uname -s)" == "Linux" ]; then
    host_option="--add-host host.docker.internal:host-gateway"
fi

ensure_conjur_up

if [[ -z $(docker-compose ps -q kong) ]]; then
    announce "Starting Kong in Docker"
    docker-compose up -d kong
    docker-compose exec kong kong start
else
    announce "Reloading Kong config"
    docker-compose exec kong kong reload
fi
sleep 10

admin_api_key="$(docker-compose exec -T conjur conjurctl role retrieve-key dev:user:admin | tr -d '\r')"

docker run \
    -v "$(pwd):/opt/openapi" \
    -w "/opt/openapi" \
    -e ADMIN_API_KEY="$admin_api_key" \
    --network "openapi-spec" \
    bash:latest examples/kong/run
