=begin
#Conjur

#This is an API definition for CyberArk DAP (part of AAM) and Conjur OSS v10+. You can find out more at [Conjur](https://www.conjur.org/) and [AAM](https://www.cyberark.com/products/privileged-account-security-solution/application-access-manager/) pages.

The version of the OpenAPI document: 0.0.1
Contact: conj_maintainers@cyberark.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PoliciesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PoliciesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PoliciesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PoliciesApi' do
    it 'should create an instance of PoliciesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PoliciesApi)
    end
  end

  # unit tests for load_policy
  # Loads or replaces a Conjur policy document.
  # Loads or replaces a Conjur policy document.  **Any policy data which already exists on the server but is not explicitly specified in the new policy file will be deleted!**.
  # @param account Organization account name
  # @param identifier ID of the policy to load (root if no root policy has been loaded yet)
  # @param body Policy
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'load_policy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for modify_policy
  # Modifies an existing Conjur policy.
  # Modifies an existing Conjur policy. Data may be explicitly deleted using the &#x60;!delete&#x60;, &#x60;!revoke&#x60;, and &#x60;!deny&#x60; statements. Unlike &#x60;replace&#x60; mode, no data is ever implicitly deleted.  ##### Permissions required &#x60;create&#x60; privilege on the policy.
  # @param account Organization account name
  # @param identifier ID of the policy to update
  # @param body Policy
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'modify_policy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_policy
  # Adds data to the existing Conjur policy.
  # Adds data to the existing Conjur policy. Deletions are not allowed. Any policy objects that exist on the server but are omitted from the policy file will not be deleted and any explicit deletions in the policy file will result in an error. ##### Permissions required &#x60;create&#x60; privilege on the policy.
  # @param account Organization account name
  # @param identifier ID of the policy to update
  # @param body Policy
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_policy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
