=begin
#Conjur

#This is an API definition for CyberArk DAP (part of AAM) and Conjur OSS v10+. You can find out more at [Conjur](https://www.conjur.org/) and [AAM](https://www.cyberark.com/products/privileged-account-security-solution/application-access-manager/) pages.

The version of the OpenAPI document: 0.0.1
Contact: conj_maintainers@cyberark.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PublicKeysApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PublicKeysApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PublicKeysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PublicKeysApi' do
    it 'should create an instance of PublicKeysApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PublicKeysApi)
    end
  end

  # unit tests for show_public_keys
  # Shows all public keys for a resource.
  # Shows all public keys for a resource as newline delimited string for compatibility with the authorized_keys SSH format.  Returns an empty string if the resource does not exist, to prevent attackers from determining whether a resource exists.
  # @param account Organization account name
  # @param kind Type of resource
  # @param identifier ID of the resource for which to get the information about
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'show_public_keys test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
