name: Check Commits

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, edited]

jobs:
  force_rebase:
    runs-on: ubuntu-latest
    name: Enforce Rebasing
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for rebase
        uses: cyberark/enforce-rebase@v2
        with:
          default-branch: main

  check_commit:
    runs-on: ubuntu-latest
    name: Check commit style
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit style
        uses: cyberark/enforce-commit-style@v1
