name: K8s Inject Test

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, edited]
    paths:
    - 'test/python/k8s/**'
    - 'spec/authentication.yaml'

  schedule:
    - cron: '0 17 * * *'

jobs:
  run-k8s-inject-test-script:
    name: Run K8s Inject Test Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.2.1

      - name: Create k8s KinD Cluster
        uses: helm/kind-action@v1.1.0

      - name: Run Test Scripts
        run: ./test/python/k8s/start
