name: Test Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, edited]

jobs:
  pylint:
    runs-on: ubuntu-latest
    name: Python Test Linting
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Lint the tests
        run: ./bin/lint_tests

  spectral:
    runs-on: ubuntu-latest
    name: Spec File Linting
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Lint Spec
        run: ./bin/lint_spec
