name: Test Code Quality

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        types: [opened, synchronize, reopened, edited]

jobs:
    pylint:
        runs-on: ubuntu-latest
        name: Python Test Linting
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'

            - name: Generate python client
              run: ./bin/generate_client

            - name: Install the client
              run: python -m pip install out/python pylint

            - name: Run Pylint
              run: pylint test/python --rcfile=test/config/.pylintrc
